// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpQh5WPkJpgzL2drCeRDA1wEO34zCPC-k',
    appId: '1:441830633759:web:9260ca69c3f18f6fd6802a',
    messagingSenderId: '441830633759',
    projectId: 'audiorecordingapp-e9a50',
    authDomain: 'audiorecordingapp-e9a50.firebaseapp.com',
    storageBucket: 'audiorecordingapp-e9a50.appspot.com',
    measurementId: 'G-2YV4LFN7QC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPvsGKLxa8ju4q34CtpD2DYKKOkuTCtSQ',
    appId: '1:441830633759:android:0cda2d108e9ecc9cd6802a',
    messagingSenderId: '441830633759',
    projectId: 'audiorecordingapp-e9a50',
    storageBucket: 'audiorecordingapp-e9a50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD63NjTbLAPzqOQX8T-ufX8KS-B3MpdqQ',
    appId: '1:441830633759:ios:a115e194ec97c79ed6802a',
    messagingSenderId: '441830633759',
    projectId: 'audiorecordingapp-e9a50',
    storageBucket: 'audiorecordingapp-e9a50.appspot.com',
    iosBundleId: 'com.ankita.recordngapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD63NjTbLAPzqOQX8T-ufX8KS-B3MpdqQ',
    appId: '1:441830633759:ios:244ff39b6a0e818bd6802a',
    messagingSenderId: '441830633759',
    projectId: 'audiorecordingapp-e9a50',
    storageBucket: 'audiorecordingapp-e9a50.appspot.com',
    iosBundleId: 'com.ankita.recordngapp.RunnerTests',
  );
}
